spring:
  cloud:
    aws:
      credentials.access-key: ${S3_ACCESS_KEY}
      credentials.secret-key: ${S3_SECRET_KEY}
      s3.bucket: main-test-aream
      region.static: ap-northeast-2
      stack.auto: false
  jwt:
    key: yourSecretKey123r345swergsdfg23466
    access-token-expiration-minutes: 40
    refresh-token-expiration-minutes: 420
  mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: /h2 # 경로
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:test

  jpa:
    hibernate:
      ddl-auto: update    #스키마 직접 생성 (자동생성 X)
    show-sql: true        # SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # SQL pretty print
        jdbc:
          time_zone: Asia/Seoul   # 서버 시간 서울로 변경


  logging:
    level:
      org.springframework: DEBUG
      org.hibernate.sql: DEBUG
      org.hibernate.type.descriptor.sql: DEBUG #show parameter binding

  mail:
    address:
      admin: admin@gmail.com