spring:
  profiles:
    active: test
  security:
    user:
      name: admin@gmail.com
      password: 1234
      roles: ROLE_ADMIN
  redis:
    host: localhost
    port: 6379

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    view-names: thymeleaf/*

cloud:
  aws:
    credentials.access-key:
    credentials.secret-key:
    s3.bucket: main-test-aream
    region.static: ap-northeast-2
    stack.auto: false

# test 프로파일 설정
test:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      h2:
        console:
          enabled: true
          path: /h2
          settings:
            web-allow-others: true
      datasource:
        driver-class-name: org.h2.Driver
        username: sa
        password:
        url: jdbc:h2:mem:testdb
        sql:
          init:
            schema-locations: classpath*:db/schema.sql
            data-locations: classpath*:db/data.sql
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            format_sql: true
            jdbc:
              time_zone: Asia/Seoul
      sql:
        init:
          schema-locations: classpath*:db/schema.sql
          data-locations: classpath*:db/data.sql

jwt:
  key: yourSecretKey123r345swergsdfg123345345656687678
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: admin@gmail.com
