spring:
  profiles:
    active: test

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    view-names: thymeleaf/*

cloud:
  aws:
    credentials.access-key: ${S3_ACCESS_KEY}
    credentials.secret-key: ${S3_SECRET_KEY}
    s3.bucket: main-test-aream
    region.static: ap-northeast-2
    stack.auto: false

# test 프로파일 설정
test:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      h2:
        console:
          enabled: true
          path: /h2
          settings:
            web-allow-others: true
      datasource:
        driver-class-name: org.h2.Driver
        username: sa
        password:
        url: jdbc:h2:mem:test
        sql:
          init:
            schema-locations: classpath*:db/schema.sql
            data-locations: classpath*:db/data.sql
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            format_sql: true
            jdbc:
              time_zone: Asia/Seoul
      sql:
        init:
          schema-locations: classpath*:db/schema.sql
          data-locations: classpath*:db/data.sql

jwt:
  key: yourSecretKey123r345swergsdfg
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: admin@gmail.com
